version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - $GO_LOCAL_PORT:$GO_DOCKER_PORT
    environment:
      PORT: $GO_DOCKER_PORT
      DB_HOST: mongodb
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      MONGODB_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
      - eureka_server

  # Eureka server
  eureka_server:
    image: netflixoss/eureka
    ports:
      - 8761:8761

volumes:
  mongo_data: {}

  # local->container

